basePath: /
consumes:
    - application/json
definitions:
    Product:
        description: Represents the product for this app
        properties:
            changedon:
                description: the product editing time
                example: "2022-01-01"
                format: date-time
                type: string
                x-go-name: ChangedOn
            createdon:
                description: the product creation time
                example: "2022-01-01"
                format: date-time
                type: string
                x-go-name: CreatedOn
            description:
                description: the description for product description
                type: string
                x-go-name: Description
            id:
                description: the id for product
                format: int64
                type: integer
                uniqueItems: true
                x-go-name: ID
            name:
                description: the name for product name
                type: string
                x-go-name: Name
        required:
            - id
            - name
        type: object
        x-go-package: sevgifidan.com/urunYonetimi/models
host: localhost:8080
info:
    description: Documantation of our awesome API
    title: Product Management
    version: 1.0.0
paths:
    /api/products:
        get:
            description: Get all products
            operationId: getProducts
            produces:
                - application/json
            responses:
                "200":
                    description: product response
                    schema:
                        items:
                            $ref: '#/definitions/Product'
                        type: array
            tags:
                - read
        post:
            description: Adding a product
            operationId: postProduct
            parameters:
                - in: body
                  name: Body
                  schema:
                    $ref: '#/definitions/Product'
            produces:
                - application/json
            responses:
                "200":
                    description: product response
            tags:
                - write
    /api/products/{id}:
        delete:
            description: Deleting a product
            operationId: deleteProduct
            parameters:
                - in: path
                  name: id
                  required: true
                  type: integer
                - in: body
                  name: Body
                  schema:
                    $ref: '#/definitions/Product'
            produces:
                - application/json
            responses:
                "200":
                    description: product response
            tags:
                - write
        get:
            description: Get a products
            operationId: getProduct
            parameters:
                - in: path
                  name: id
                  required: true
                  type: integer
            produces:
                - application/json
            responses:
                "200":
                    description: product response
                    schema:
                        items:
                            $ref: '#/definitions/Product'
                        type: array
            tags:
                - read
        put:
            description: Updating a product
            operationId: putProduct
            parameters:
                - in: path
                  name: id
                  required: true
                  type: integer
                - in: body
                  name: Body
                  schema:
                    $ref: '#/definitions/Product'
            produces:
                - application/json
            responses:
                "200":
                    description: product response
            tags:
                - write
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
